<?php
/**
 * Language Configuration
 * Manages multiple language support for the e-commerce site
 */

// Start session if not already started
if (session_status() == PHP_SESSION_NONE) {
    session_start();
}

// Available languages
$available_languages = [
    'en' => [
        'name' => 'English',
        'flag' => '🇬🇧',
        'code' => 'EN'
    ],
    'es' => [
        'name' => 'Español',
        'flag' => '🇪🇸',
        'code' => 'ES'
    ],
    'fr' => [
        'name' => 'Français',
        'flag' => '🇫🇷',
        'code' => 'FR'
    ],
    'de' => [
        'name' => 'Deutsch',
        'flag' => '🇩🇪',
        'code' => 'DE'
    ]
];

// Set default language
if (!isset($_SESSION['language'])) {
    $_SESSION['language'] = 'en';
}

// Get current language
$current_language = $_SESSION['language'];

// Validate current language
if (!array_key_exists($current_language, $available_languages)) {
    $_SESSION['language'] = 'en';
    $current_language = 'en';
}

/**
 * Get translation for a key
 */
function translate($key) {
    global $translations, $current_language;

    // If translations not loaded, load them
    if (!isset($translations)) {
        load_translations();
    }

    // Return translation if exists, otherwise return the key
    return $translations[$current_language][$key] ?? $translations['en'][$key] ?? $key;
}

/**
 * Shorthand function for translation
 */
function t($key) {
    return translate($key);
}

/**
 * Load translations
 */
function load_translations() {
    global $translations;

    $translations = [
        'en' => [
            // Header & Navigation
            'search_placeholder' => 'Search phones, laptops, cameras...',
            'tech_revival' => 'Bring Retired Tech',
            'home' => 'HOME',
            'shop' => 'SHOP',
            'mobile_devices' => 'Mobile Devices',
            'smartphones' => 'Smartphones',
            'ipads' => 'iPads',
            'computing' => 'Computing',
            'laptops' => 'Laptops',
            'desktops' => 'Desktops',
            'photography_video' => 'Photography & Video',
            'cameras' => 'Cameras',
            'video_equipment' => 'Video Equipment',
            'shop_all' => 'Shop All',
            'new_arrivals' => 'New Arrivals',
            'latest_tech_gadgets' => 'Latest tech gadgets',
            'shop_now' => 'Shop Now',
            'repair_studio' => 'REPAIR STUDIO',
            'device_drop' => 'DEVICE DROP',
            'more' => 'MORE',
            'contact' => 'Contact',
            'terms_conditions' => 'Terms & Conditions',
            'flash_deal' => '⚡ FLASH DEAL',
            'shop_by_brands' => 'SHOP BY BRANDS',
            'all_brands' => 'All Brands',
            'all_products' => 'All Products',

            // User menu & Authentication
            'profile_picture' => 'Profile Picture',
            'language' => 'Language',
            'dark_mode' => 'Dark Mode',
            'my_orders' => 'My Orders',
            'wishlist' => 'Wishlist',
            'notifications' => 'Notifications',
            'admin_panel' => 'Admin Panel',
            'logout' => 'Logout',
            'register' => 'Register',
            'login' => 'Login',
            'email' => 'Email',
            'password' => 'Password',
            'confirm_password' => 'Confirm Password',
            'first_name' => 'First Name',
            'last_name' => 'Last Name',
            'phone' => 'Phone',
            'address' => 'Address',
            'city' => 'City',
            'country' => 'Country',
            'create_account' => 'Create Account',
            'sign_in' => 'Sign In',
            'forgot_password' => 'Forgot Password?',
            'remember_me' => 'Remember Me',

            // Common Actions
            'welcome' => 'Welcome',
            'add_to_cart' => 'Add to Cart',
            'buy_now' => 'Buy Now',
            'price' => 'Price',
            'quantity' => 'Quantity',
            'total' => 'Total',
            'subtotal' => 'Subtotal',
            'checkout' => 'Checkout',
            'continue_shopping' => 'Continue Shopping',
            'view_cart' => 'View Cart',
            'empty_cart' => 'Empty Cart',
            'remove' => 'Remove',
            'update' => 'Update',
            'save' => 'Save',
            'cancel' => 'Cancel',
            'yes' => 'Yes',
            'no' => 'No',
            'ok' => 'OK',
            'error' => 'Error',
            'success' => 'Success',
            'warning' => 'Warning',
            'info' => 'Information',
            'loading' => 'Loading...',
            'edit' => 'Edit',
            'delete' => 'Delete',
            'add' => 'Add',
            'search' => 'Search',
            'filter' => 'Filter',
            'sort' => 'Sort',
            'apply' => 'Apply',
            'reset' => 'Reset',
            'submit' => 'Submit',
            'back' => 'Back',
            'next' => 'Next',
            'previous' => 'Previous',
            'close' => 'Close',

            // Product & Shopping
            'product_name' => 'Product Name',
            'product_description' => 'Product Description',
            'product_details' => 'Product Details',
            'product_specifications' => 'Product Specifications',
            'product_reviews' => 'Product Reviews',
            'add_to_wishlist' => 'Add to Wishlist',
            'remove_from_wishlist' => 'Remove from Wishlist',
            'in_stock' => 'In Stock',
            'out_of_stock' => 'Out of Stock',
            'limited_stock' => 'Limited Stock',
            'condition' => 'Condition',
            'brand' => 'Brand',
            'category' => 'Category',
            'sku' => 'SKU',
            'warranty' => 'Warranty',
            'rating' => 'Rating',
            'reviews' => 'Reviews',
            'related_products' => 'Related Products',
            'recently_viewed' => 'Recently Viewed',
            'featured_products' => 'Featured Products',

            // Cart & Checkout
            'shopping_cart' => 'Shopping Cart',
            'cart_empty' => 'Your cart is empty',
            'cart_items' => 'Cart Items',
            'item_added_to_cart' => 'Item added to cart',
            'item_removed_from_cart' => 'Item removed from cart',
            'cart_updated' => 'Cart updated',
            'proceed_to_checkout' => 'Proceed to Checkout',
            'billing_address' => 'Billing Address',
            'shipping_address' => 'Shipping Address',
            'payment_method' => 'Payment Method',
            'order_summary' => 'Order Summary',
            'shipping_cost' => 'Shipping Cost',
            'tax' => 'Tax',
            'discount' => 'Discount',
            'grand_total' => 'Grand Total',
            'place_order' => 'Place Order',
            'order_placed' => 'Order Placed Successfully',
            'order_number' => 'Order Number',
            'order_date' => 'Order Date',
            'order_status' => 'Order Status',

            // Order Management
            'pending' => 'Pending',
            'processing' => 'Processing',
            'shipped' => 'Shipped',
            'delivered' => 'Delivered',
            'cancelled' => 'Cancelled',
            'refunded' => 'Refunded',
            'track_order' => 'Track Order',
            'order_history' => 'Order History',
            'reorder' => 'Reorder',
            'download_receipt' => 'Download Receipt',

            // Admin Panel
            'dashboard' => 'Dashboard',
            'products' => 'Products',
            'categories' => 'Categories',
            'brands' => 'Brands',
            'orders' => 'Orders',
            'customers' => 'Customers',
            'reports' => 'Reports',
            'settings' => 'Settings',
            'add_product' => 'Add Product',
            'edit_product' => 'Edit Product',
            'delete_product' => 'Delete Product',
            'add_category' => 'Add Category',
            'edit_category' => 'Edit Category',
            'delete_category' => 'Delete Category',
            'add_brand' => 'Add Brand',
            'edit_brand' => 'Edit Brand',
            'delete_brand' => 'Delete Brand',
            'manage_orders' => 'Manage Orders',
            'view_order' => 'View Order',
            'update_status' => 'Update Status',

            // Repair Services
            'repair_services' => 'Repair Services',
            'device_repair' => 'Device Repair',
            'screen_replacement' => 'Screen Replacement',
            'battery_replacement' => 'Battery Replacement',
            'water_damage' => 'Water Damage',
            'software_issues' => 'Software Issues',
            'hardware_repair' => 'Hardware Repair',
            'diagnosis' => 'Diagnosis',
            'repair_quote' => 'Repair Quote',
            'book_repair' => 'Book Repair',
            'repair_appointment' => 'Repair Appointment',
            'appointment_date' => 'Appointment Date',
            'appointment_time' => 'Appointment Time',
            'repair_specialist' => 'Repair Specialist',
            'repair_status' => 'Repair Status',
            'estimated_cost' => 'Estimated Cost',
            'repair_completed' => 'Repair Completed',

            // Device Drop Service
            'device_drop_service' => 'Device Drop Service',
            'drop_off_device' => 'Drop Off Device',
            'pickup_device' => 'Pickup Device',
            'device_condition' => 'Device Condition',
            'drop_location' => 'Drop Location',
            'pickup_time' => 'Pickup Time',
            'schedule_drop' => 'Schedule Drop',
            'drop_confirmed' => 'Drop Confirmed',
            'device_received' => 'Device Received',

            // Contact & Support
            'contact_us' => 'Contact Us',
            'customer_support' => 'Customer Support',
            'send_message' => 'Send Message',
            'message_sent' => 'Message Sent',
            'support_ticket' => 'Support Ticket',
            'ticket_number' => 'Ticket Number',
            'subject' => 'Subject',
            'message' => 'Message',
            'attachments' => 'Attachments',
            'priority' => 'Priority',
            'high' => 'High',
            'medium' => 'Medium',
            'low' => 'Low',
            'urgent' => 'Urgent',

            // Legal & Information
            'privacy_policy' => 'Privacy Policy',
            'return_policy' => 'Return Policy',
            'shipping_policy' => 'Shipping Policy',
            'refund_policy' => 'Refund Policy',
            'about_us' => 'About Us',
            'faq' => 'FAQ',
            'help' => 'Help',
            'size_guide' => 'Size Guide',

            // Search & Filters
            'search_results' => 'Search Results',
            'no_results_found' => 'No results found',
            'filter_by' => 'Filter By',
            'sort_by' => 'Sort By',
            'price_range' => 'Price Range',
            'min_price' => 'Min Price',
            'max_price' => 'Max Price',
            'availability' => 'Availability',
            'customer_rating' => 'Customer Rating',
            'newest_first' => 'Newest First',
            'oldest_first' => 'Oldest First',
            'price_low_to_high' => 'Price: Low to High',
            'price_high_to_low' => 'Price: High to Low',
            'most_popular' => 'Most Popular',
            'best_rated' => 'Best Rated',

            // Notifications
            'new_notification' => 'New Notification',
            'mark_as_read' => 'Mark as Read',
            'clear_all' => 'Clear All',
            'no_notifications' => 'No notifications',

            // Forms & Validation
            'required_field' => 'This field is required',
            'invalid_email' => 'Please enter a valid email address',
            'passwords_dont_match' => 'Passwords do not match',
            'min_length' => 'Minimum length required',
            'max_length' => 'Maximum length exceeded',
            'invalid_format' => 'Invalid format',
            'please_select' => 'Please select',
            'choose_file' => 'Choose File',
            'file_uploaded' => 'File uploaded successfully',
            'upload_failed' => 'Upload failed',

            // Time & Date
            'today' => 'Today',
            'yesterday' => 'Yesterday',
            'tomorrow' => 'Tomorrow',
            'this_week' => 'This Week',
            'last_week' => 'Last Week',
            'this_month' => 'This Month',
            'last_month' => 'Last Month',
            'this_year' => 'This Year',
            'days_ago' => 'days ago',
            'hours_ago' => 'hours ago',
            'minutes_ago' => 'minutes ago',
            'just_now' => 'Just now',

            // Page Titles
            'gadget_garage' => 'Gadget Garage',
            'homepage' => 'Homepage',
            'product_page' => 'Product Page',
            'cart_page' => 'Shopping Cart',
            'checkout_page' => 'Checkout',
            'login_page' => 'Login',
            'register_page' => 'Register',
            'account_page' => 'My Account',
            'orders_page' => 'My Orders',
            'wishlist_page' => 'My Wishlist',
            'contact_page' => 'Contact Us',
            'about_page' => 'About Us',

            // Footer
            'footer_description' => 'Your trusted partner for premium refurbished tech devices and professional repair services.',
            'quick_links' => 'Quick Links',
            'customer_service' => 'Customer Service',
            'follow_us' => 'Follow Us',
            'newsletter' => 'Newsletter',
            'subscribe' => 'Subscribe',
            'email_address' => 'Email Address',
            'subscribe_newsletter' => 'Subscribe to our newsletter for updates and deals',
            'copyright' => '© 2024 Gadget Garage. All rights reserved.',

            // Meta Descriptions & SEO
            'meta_description' => 'Premium refurbished tech devices and professional repair services at Gadget Garage. Quality guaranteed.',
            'meta_keywords' => 'refurbished tech, smartphones, laptops, cameras, repair services, tech devices',

            // Homepage Specific
            'ipad_pro_title' => 'Apple IPad Pro 11<br>Ultra Retina XDR<br>Display, 256GB',
            'gadget_garage_title' => 'Gadget Garage - Premium Refurbrished Tech Devices & Repair Services',
            'shop_by_categories' => 'Shop by Categories',
            'exclusive_offers' => 'Exclusive Offers',
            'best_deals' => 'Best Deals',
            'trending_products' => 'Trending Products',
            'customer_testimonials' => 'Customer Testimonials',
            'why_choose_us' => 'Why Choose Us',
            'quality_guarantee' => 'Quality Guarantee',
            'fast_shipping' => 'Fast Shipping',
            'expert_support' => 'Expert Support',
            'secure_payment' => 'Secure Payment',
            'starting_at' => 'Starting At',
            't900_ultra_watch' => 'T900 Ultra<br>Watch',
            'kids_wireless_headphones' => 'Kids Wireless<br>Headphones',
            'starting' => 'Starting',

            // Footer Content
            'services' => 'Services',
            'device_repair' => 'Device Repair',
            'tech_support' => 'Tech Support',
            'data_recovery' => 'Data Recovery',
            'setup_services' => 'Setup Services',
            'warranty' => 'Warranty',
            'company' => 'Company',
            'careers' => 'Careers',
            'blog' => 'Blog',
            'press' => 'Press',
            'support' => 'Support',
            'help_center' => 'Help Center',
            'shipping_info' => 'Shipping Info',
            'returns' => 'Returns',
            'terms_of_service' => 'Terms of Service',
            'smartphones_footer' => 'Smartphones',
            'laptops_footer' => 'Laptops',
            'tablets' => 'Tablets',
            'cameras_footer' => 'Cameras',
            'video_equipment_footer' => 'Video Equipment',
        ],

        'es' => [
            // Header & Navigation
            'search_placeholder' => 'Buscar teléfonos, laptops, cámaras...',
            'tech_revival' => 'Traiga Tecnología Retirada',
            'home' => 'INICIO',
            'shop' => 'TIENDA',
            'mobile_devices' => 'Dispositivos Móviles',
            'smartphones' => 'Teléfonos Inteligentes',
            'ipads' => 'iPads',
            'computing' => 'Computación',
            'laptops' => 'Portátiles',
            'desktops' => 'Escritorio',
            'photography_video' => 'Fotografía y Video',
            'cameras' => 'Cámaras',
            'video_equipment' => 'Equipo de Video',
            'shop_all' => 'Comprar Todo',
            'new_arrivals' => 'Nuevas Llegadas',
            'latest_tech_gadgets' => 'Últimos gadgets tecnológicos',
            'shop_now' => 'Comprar Ahora',
            'repair_studio' => 'ESTUDIO DE REPARACIÓN',
            'device_drop' => 'ENTREGA DE DISPOSITIVO',
            'more' => 'MÁS',
            'contact' => 'Contacto',
            'terms_conditions' => 'Términos y Condiciones',
            'flash_deal' => '⚡ OFERTA FLASH',
            'shop_by_brands' => 'COMPRAR POR MARCAS',
            'all_brands' => 'Todas las Marcas',
            'all_products' => 'Todos los Productos',

            // User menu & Authentication
            'profile_picture' => 'Foto de Perfil',
            'language' => 'Idioma',
            'dark_mode' => 'Modo Oscuro',
            'my_orders' => 'Mis Pedidos',
            'wishlist' => 'Lista de Deseos',
            'notifications' => 'Notificaciones',
            'admin_panel' => 'Panel de Admin',
            'logout' => 'Cerrar Sesión',
            'register' => 'Registrarse',
            'login' => 'Iniciar Sesión',
            'email' => 'Correo Electrónico',
            'password' => 'Contraseña',
            'confirm_password' => 'Confirmar Contraseña',
            'first_name' => 'Nombre',
            'last_name' => 'Apellido',
            'phone' => 'Teléfono',
            'address' => 'Dirección',
            'city' => 'Ciudad',
            'country' => 'País',
            'create_account' => 'Crear Cuenta',
            'sign_in' => 'Iniciar Sesión',
            'forgot_password' => '¿Olvidó su contraseña?',
            'remember_me' => 'Recordarme',

            // Common Actions
            'welcome' => 'Bienvenido',
            'add_to_cart' => 'Agregar al Carrito',
            'buy_now' => 'Comprar Ahora',
            'price' => 'Precio',
            'quantity' => 'Cantidad',
            'total' => 'Total',
            'subtotal' => 'Subtotal',
            'checkout' => 'Pagar',
            'continue_shopping' => 'Seguir Comprando',
            'view_cart' => 'Ver Carrito',
            'empty_cart' => 'Vaciar Carrito',
            'remove' => 'Eliminar',
            'update' => 'Actualizar',
            'save' => 'Guardar',
            'cancel' => 'Cancelar',
            'yes' => 'Sí',
            'no' => 'No',
            'ok' => 'OK',
            'error' => 'Error',
            'success' => 'Éxito',
            'warning' => 'Advertencia',
            'info' => 'Información',
            'loading' => 'Cargando...',
            'edit' => 'Editar',
            'delete' => 'Eliminar',
            'add' => 'Agregar',
            'search' => 'Buscar',
            'filter' => 'Filtrar',
            'sort' => 'Ordenar',
            'apply' => 'Aplicar',
            'reset' => 'Restablecer',
            'submit' => 'Enviar',
            'back' => 'Atrás',
            'next' => 'Siguiente',
            'previous' => 'Anterior',
            'close' => 'Cerrar',

            // Product & Shopping
            'product_name' => 'Nombre del Producto',
            'product_description' => 'Descripción del Producto',
            'product_details' => 'Detalles del Producto',
            'product_specifications' => 'Especificaciones del Producto',
            'product_reviews' => 'Reseñas del Producto',
            'add_to_wishlist' => 'Agregar a Lista de Deseos',
            'remove_from_wishlist' => 'Quitar de Lista de Deseos',
            'in_stock' => 'En Stock',
            'out_of_stock' => 'Agotado',
            'limited_stock' => 'Stock Limitado',
            'condition' => 'Condición',
            'brand' => 'Marca',
            'category' => 'Categoría',
            'sku' => 'SKU',
            'warranty' => 'Garantía',
            'rating' => 'Calificación',
            'reviews' => 'Reseñas',
            'related_products' => 'Productos Relacionados',
            'recently_viewed' => 'Visto Recientemente',
            'featured_products' => 'Productos Destacados',

            // Cart & Checkout
            'shopping_cart' => 'Carrito de Compras',
            'cart_empty' => 'Su carrito está vacío',
            'cart_items' => 'Artículos del Carrito',
            'item_added_to_cart' => 'Artículo agregado al carrito',
            'item_removed_from_cart' => 'Artículo eliminado del carrito',
            'cart_updated' => 'Carrito actualizado',
            'proceed_to_checkout' => 'Proceder al Pago',
            'billing_address' => 'Dirección de Facturación',
            'shipping_address' => 'Dirección de Envío',
            'payment_method' => 'Método de Pago',
            'order_summary' => 'Resumen del Pedido',
            'shipping_cost' => 'Costo de Envío',
            'tax' => 'Impuesto',
            'discount' => 'Descuento',
            'grand_total' => 'Total General',
            'place_order' => 'Realizar Pedido',
            'order_placed' => 'Pedido Realizado Exitosamente',
            'order_number' => 'Número de Pedido',
            'order_date' => 'Fecha del Pedido',
            'order_status' => 'Estado del Pedido',

            // Order Management
            'pending' => 'Pendiente',
            'processing' => 'Procesando',
            'shipped' => 'Enviado',
            'delivered' => 'Entregado',
            'cancelled' => 'Cancelado',
            'refunded' => 'Reembolsado',
            'track_order' => 'Rastrear Pedido',
            'order_history' => 'Historial de Pedidos',
            'reorder' => 'Volver a Pedir',
            'download_receipt' => 'Descargar Recibo',

            // Admin Panel
            'dashboard' => 'Panel de Control',
            'products' => 'Productos',
            'categories' => 'Categorías',
            'brands' => 'Marcas',
            'orders' => 'Pedidos',
            'customers' => 'Clientes',
            'reports' => 'Reportes',
            'settings' => 'Configuración',
            'add_product' => 'Agregar Producto',
            'edit_product' => 'Editar Producto',
            'delete_product' => 'Eliminar Producto',
            'add_category' => 'Agregar Categoría',
            'edit_category' => 'Editar Categoría',
            'delete_category' => 'Eliminar Categoría',
            'add_brand' => 'Agregar Marca',
            'edit_brand' => 'Editar Marca',
            'delete_brand' => 'Eliminar Marca',
            'manage_orders' => 'Gestionar Pedidos',
            'view_order' => 'Ver Pedido',
            'update_status' => 'Actualizar Estado',

            // Repair Services
            'repair_services' => 'Servicios de Reparación',
            'device_repair' => 'Reparación de Dispositivos',
            'screen_replacement' => 'Reemplazo de Pantalla',
            'battery_replacement' => 'Reemplazo de Batería',
            'water_damage' => 'Daño por Agua',
            'software_issues' => 'Problemas de Software',
            'hardware_repair' => 'Reparación de Hardware',
            'diagnosis' => 'Diagnóstico',
            'repair_quote' => 'Cotización de Reparación',
            'book_repair' => 'Reservar Reparación',
            'repair_appointment' => 'Cita de Reparación',
            'appointment_date' => 'Fecha de Cita',
            'appointment_time' => 'Hora de Cita',
            'repair_specialist' => 'Especialista en Reparación',
            'repair_status' => 'Estado de Reparación',
            'estimated_cost' => 'Costo Estimado',
            'repair_completed' => 'Reparación Completada',

            // Device Drop Service
            'device_drop_service' => 'Servicio de Entrega de Dispositivos',
            'drop_off_device' => 'Entregar Dispositivo',
            'pickup_device' => 'Recoger Dispositivo',
            'device_condition' => 'Condición del Dispositivo',
            'drop_location' => 'Ubicación de Entrega',
            'pickup_time' => 'Hora de Recogida',
            'schedule_drop' => 'Programar Entrega',
            'drop_confirmed' => 'Entrega Confirmada',
            'device_received' => 'Dispositivo Recibido',

            // Contact & Support
            'contact_us' => 'Contáctanos',
            'customer_support' => 'Atención al Cliente',
            'send_message' => 'Enviar Mensaje',
            'message_sent' => 'Mensaje Enviado',
            'support_ticket' => 'Ticket de Soporte',
            'ticket_number' => 'Número de Ticket',
            'subject' => 'Asunto',
            'message' => 'Mensaje',
            'attachments' => 'Archivos Adjuntos',
            'priority' => 'Prioridad',
            'high' => 'Alta',
            'medium' => 'Media',
            'low' => 'Baja',
            'urgent' => 'Urgente',

            // Legal & Information
            'privacy_policy' => 'Política de Privacidad',
            'return_policy' => 'Política de Devoluciones',
            'shipping_policy' => 'Política de Envío',
            'refund_policy' => 'Política de Reembolso',
            'about_us' => 'Acerca de Nosotros',
            'faq' => 'Preguntas Frecuentes',
            'help' => 'Ayuda',
            'size_guide' => 'Guía de Tallas',

            // Search & Filters
            'search_results' => 'Resultados de Búsqueda',
            'no_results_found' => 'No se encontraron resultados',
            'filter_by' => 'Filtrar Por',
            'sort_by' => 'Ordenar Por',
            'price_range' => 'Rango de Precio',
            'min_price' => 'Precio Mínimo',
            'max_price' => 'Precio Máximo',
            'availability' => 'Disponibilidad',
            'customer_rating' => 'Calificación del Cliente',
            'newest_first' => 'Más Nuevo Primero',
            'oldest_first' => 'Más Antiguo Primero',
            'price_low_to_high' => 'Precio: Menor a Mayor',
            'price_high_to_low' => 'Precio: Mayor a Menor',
            'most_popular' => 'Más Popular',
            'best_rated' => 'Mejor Calificado',

            // Notifications
            'new_notification' => 'Nueva Notificación',
            'mark_as_read' => 'Marcar como Leído',
            'clear_all' => 'Limpiar Todo',
            'no_notifications' => 'Sin notificaciones',

            // Forms & Validation
            'required_field' => 'Este campo es obligatorio',
            'invalid_email' => 'Por favor ingrese un correo electrónico válido',
            'passwords_dont_match' => 'Las contraseñas no coinciden',
            'min_length' => 'Longitud mínima requerida',
            'max_length' => 'Longitud máxima excedida',
            'invalid_format' => 'Formato inválido',
            'please_select' => 'Por favor seleccione',
            'choose_file' => 'Elegir Archivo',
            'file_uploaded' => 'Archivo subido exitosamente',
            'upload_failed' => 'Error al subir',

            // Time & Date
            'today' => 'Hoy',
            'yesterday' => 'Ayer',
            'tomorrow' => 'Mañana',
            'this_week' => 'Esta Semana',
            'last_week' => 'Semana Pasada',
            'this_month' => 'Este Mes',
            'last_month' => 'Mes Pasado',
            'this_year' => 'Este Año',
            'days_ago' => 'días atrás',
            'hours_ago' => 'horas atrás',
            'minutes_ago' => 'minutos atrás',
            'just_now' => 'Justo ahora',

            // Page Titles
            'gadget_garage' => 'Garaje de Gadgets',
            'homepage' => 'Página Principal',
            'product_page' => 'Página de Producto',
            'cart_page' => 'Carrito de Compras',
            'checkout_page' => 'Pagar',
            'login_page' => 'Iniciar Sesión',
            'register_page' => 'Registrarse',
            'account_page' => 'Mi Cuenta',
            'orders_page' => 'Mis Pedidos',
            'wishlist_page' => 'Mi Lista de Deseos',
            'contact_page' => 'Contáctanos',
            'about_page' => 'Acerca de Nosotros',

            // Footer
            'footer_description' => 'Su socio de confianza para dispositivos tecnológicos reacondicionados premium y servicios de reparación profesionales.',
            'quick_links' => 'Enlaces Rápidos',
            'customer_service' => 'Atención al Cliente',
            'follow_us' => 'Síguenos',
            'newsletter' => 'Boletín',
            'subscribe' => 'Suscribirse',
            'email_address' => 'Dirección de Correo',
            'subscribe_newsletter' => 'Suscríbete a nuestro boletín para actualizaciones y ofertas',
            'copyright' => '© 2024 Garaje de Gadgets. Todos los derechos reservados.',

            // Meta Descriptions & SEO
            'meta_description' => 'Dispositivos tecnológicos reacondicionados premium y servicios de reparación profesionales en Garaje de Gadgets. Calidad garantizada.',
            'meta_keywords' => 'tecnología reacondicionada, smartphones, laptops, cámaras, servicios de reparación, dispositivos tecnológicos',

            // Homepage Specific
            'ipad_pro_title' => 'Apple IPad Pro 11<br>Pantalla Ultra Retina XDR<br>, 256GB',
            'gadget_garage_title' => 'Garaje de Gadgets - Dispositivos Tecnológicos Reacondicionados Premium y Servicios de Reparación',
            'shop_by_categories' => 'Comprar por Categorías',
            'exclusive_offers' => 'Ofertas Exclusivas',
            'best_deals' => 'Mejores Ofertas',
            'trending_products' => 'Productos Tendencia',
            'customer_testimonials' => 'Testimonios de Clientes',
            'why_choose_us' => 'Por Qué Elegirnos',
            'quality_guarantee' => 'Garantía de Calidad',
            'fast_shipping' => 'Envío Rápido',
            'expert_support' => 'Soporte Experto',
            'secure_payment' => 'Pago Seguro',
            'starting_at' => 'Comenzando en',
            't900_ultra_watch' => 'Reloj T900<br>Ultra',
            'kids_wireless_headphones' => 'Auriculares Inalámbricos<br>Para Niños',
            'starting' => 'Comenzando',

            // Footer Content
            'services' => 'Servicios',
            'device_repair' => 'Reparación de Dispositivos',
            'tech_support' => 'Soporte Técnico',
            'data_recovery' => 'Recuperación de Datos',
            'setup_services' => 'Servicios de Configuración',
            'warranty' => 'Garantía',
            'company' => 'Empresa',
            'careers' => 'Carreras',
            'blog' => 'Blog',
            'press' => 'Prensa',
            'support' => 'Soporte',
            'help_center' => 'Centro de Ayuda',
            'shipping_info' => 'Información de Envío',
            'returns' => 'Devoluciones',
            'terms_of_service' => 'Términos de Servicio',
            'smartphones_footer' => 'Teléfonos Inteligentes',
            'laptops_footer' => 'Portátiles',
            'tablets' => 'Tabletas',
            'cameras_footer' => 'Cámaras',
            'video_equipment_footer' => 'Equipo de Video',
        ],

        'fr' => [
            // Header & Navigation
            'search_placeholder' => 'Rechercher téléphones, ordinateurs portables, caméras...',
            'tech_revival' => 'Apportez la Technologie Retirée',
            'home' => 'ACCUEIL',
            'shop' => 'BOUTIQUE',
            'mobile_devices' => 'Appareils Mobiles',
            'smartphones' => 'Smartphones',
            'ipads' => 'iPads',
            'computing' => 'Informatique',
            'laptops' => 'Ordinateurs Portables',
            'desktops' => 'Ordinateurs de Bureau',
            'photography_video' => 'Photographie et Vidéo',
            'cameras' => 'Caméras',
            'video_equipment' => 'Équipement Vidéo',
            'shop_all' => 'Tout Acheter',
            'new_arrivals' => 'Nouvelles Arrivées',
            'latest_tech_gadgets' => 'Derniers gadgets technologiques',
            'shop_now' => 'Acheter Maintenant',
            'repair_studio' => 'STUDIO DE RÉPARATION',
            'device_drop' => 'DÉPÔT D\'APPAREIL',
            'more' => 'PLUS',
            'contact' => 'Contact',
            'terms_conditions' => 'Termes et Conditions',
            'flash_deal' => '⚡ OFFRE FLASH',
            'shop_by_brands' => 'ACHETER PAR MARQUES',
            'all_brands' => 'Toutes les Marques',
            'all_products' => 'Tous les Produits',

            // User menu & Authentication
            'profile_picture' => 'Photo de Profil',
            'language' => 'Langue',
            'dark_mode' => 'Mode Sombre',
            'my_orders' => 'Mes Commandes',
            'wishlist' => 'Liste de Souhaits',
            'notifications' => 'Notifications',
            'admin_panel' => 'Panneau Admin',
            'logout' => 'Se Déconnecter',
            'register' => 'S\'inscrire',
            'login' => 'Se Connecter',
            'email' => 'Email',
            'password' => 'Mot de Passe',
            'confirm_password' => 'Confirmer le Mot de Passe',
            'first_name' => 'Prénom',
            'last_name' => 'Nom de Famille',
            'phone' => 'Téléphone',
            'address' => 'Adresse',
            'city' => 'Ville',
            'country' => 'Pays',
            'create_account' => 'Créer un Compte',
            'sign_in' => 'Se Connecter',
            'forgot_password' => 'Mot de passe oublié?',
            'remember_me' => 'Se souvenir de moi',

            // Common Actions
            'welcome' => 'Bienvenue',
            'add_to_cart' => 'Ajouter au Panier',
            'buy_now' => 'Acheter Maintenant',
            'price' => 'Prix',
            'quantity' => 'Quantité',
            'total' => 'Total',
            'subtotal' => 'Sous-total',
            'checkout' => 'Commander',
            'continue_shopping' => 'Continuer les Achats',
            'view_cart' => 'Voir le Panier',
            'empty_cart' => 'Vider le Panier',
            'remove' => 'Supprimer',
            'update' => 'Mettre à Jour',
            'save' => 'Sauvegarder',
            'cancel' => 'Annuler',
            'yes' => 'Oui',
            'no' => 'Non',
            'ok' => 'OK',
            'error' => 'Erreur',
            'success' => 'Succès',
            'warning' => 'Avertissement',
            'info' => 'Information',
            'loading' => 'Chargement...',
            'edit' => 'Modifier',
            'delete' => 'Supprimer',
            'add' => 'Ajouter',
            'search' => 'Rechercher',
            'filter' => 'Filtrer',
            'sort' => 'Trier',
            'apply' => 'Appliquer',
            'reset' => 'Réinitialiser',
            'submit' => 'Soumettre',
            'back' => 'Retour',
            'next' => 'Suivant',
            'previous' => 'Précédent',
            'close' => 'Fermer',

            // Product & Shopping
            'product_name' => 'Nom du Produit',
            'product_description' => 'Description du Produit',
            'product_details' => 'Détails du Produit',
            'product_specifications' => 'Spécifications du Produit',
            'product_reviews' => 'Avis sur le Produit',
            'add_to_wishlist' => 'Ajouter à la Liste de Souhaits',
            'remove_from_wishlist' => 'Retirer de la Liste de Souhaits',
            'in_stock' => 'En Stock',
            'out_of_stock' => 'Rupture de Stock',
            'limited_stock' => 'Stock Limité',
            'condition' => 'État',
            'brand' => 'Marque',
            'category' => 'Catégorie',
            'sku' => 'SKU',
            'warranty' => 'Garantie',
            'rating' => 'Évaluation',
            'reviews' => 'Avis',
            'related_products' => 'Produits Connexes',
            'recently_viewed' => 'Récemment Consultés',
            'featured_products' => 'Produits Vedettes',

            // Cart & Checkout
            'shopping_cart' => 'Panier',
            'cart_empty' => 'Votre panier est vide',
            'cart_items' => 'Articles du Panier',
            'item_added_to_cart' => 'Article ajouté au panier',
            'item_removed_from_cart' => 'Article retiré du panier',
            'cart_updated' => 'Panier mis à jour',
            'proceed_to_checkout' => 'Procéder au Paiement',
            'billing_address' => 'Adresse de Facturation',
            'shipping_address' => 'Adresse de Livraison',
            'payment_method' => 'Méthode de Paiement',
            'order_summary' => 'Résumé de Commande',
            'shipping_cost' => 'Frais de Livraison',
            'tax' => 'Taxe',
            'discount' => 'Remise',
            'grand_total' => 'Total Général',
            'place_order' => 'Passer Commande',
            'order_placed' => 'Commande Passée avec Succès',
            'order_number' => 'Numéro de Commande',
            'order_date' => 'Date de Commande',
            'order_status' => 'Statut de Commande',

            // Order Management
            'pending' => 'En Attente',
            'processing' => 'En Traitement',
            'shipped' => 'Expédié',
            'delivered' => 'Livré',
            'cancelled' => 'Annulé',
            'refunded' => 'Remboursé',
            'track_order' => 'Suivre la Commande',
            'order_history' => 'Historique des Commandes',
            'reorder' => 'Recommander',
            'download_receipt' => 'Télécharger le Reçu',

            // Admin Panel
            'dashboard' => 'Tableau de Bord',
            'products' => 'Produits',
            'categories' => 'Catégories',
            'brands' => 'Marques',
            'orders' => 'Commandes',
            'customers' => 'Clients',
            'reports' => 'Rapports',
            'settings' => 'Paramètres',
            'add_product' => 'Ajouter Produit',
            'edit_product' => 'Modifier Produit',
            'delete_product' => 'Supprimer Produit',
            'add_category' => 'Ajouter Catégorie',
            'edit_category' => 'Modifier Catégorie',
            'delete_category' => 'Supprimer Catégorie',
            'add_brand' => 'Ajouter Marque',
            'edit_brand' => 'Modifier Marque',
            'delete_brand' => 'Supprimer Marque',
            'manage_orders' => 'Gérer les Commandes',
            'view_order' => 'Voir Commande',
            'update_status' => 'Mettre à Jour le Statut',

            // Repair Services
            'repair_services' => 'Services de Réparation',
            'device_repair' => 'Réparation d\'Appareils',
            'screen_replacement' => 'Remplacement d\'Écran',
            'battery_replacement' => 'Remplacement de Batterie',
            'water_damage' => 'Dégât des Eaux',
            'software_issues' => 'Problèmes Logiciels',
            'hardware_repair' => 'Réparation Matérielle',
            'diagnosis' => 'Diagnostic',
            'repair_quote' => 'Devis de Réparation',
            'book_repair' => 'Réserver Réparation',
            'repair_appointment' => 'Rendez-vous de Réparation',
            'appointment_date' => 'Date du Rendez-vous',
            'appointment_time' => 'Heure du Rendez-vous',
            'repair_specialist' => 'Spécialiste en Réparation',
            'repair_status' => 'Statut de Réparation',
            'estimated_cost' => 'Coût Estimé',
            'repair_completed' => 'Réparation Terminée',

            // Device Drop Service
            'device_drop_service' => 'Service de Dépôt d\'Appareils',
            'drop_off_device' => 'Déposer l\'Appareil',
            'pickup_device' => 'Récupérer l\'Appareil',
            'device_condition' => 'État de l\'Appareil',
            'drop_location' => 'Lieu de Dépôt',
            'pickup_time' => 'Heure de Récupération',
            'schedule_drop' => 'Programmer le Dépôt',
            'drop_confirmed' => 'Dépôt Confirmé',
            'device_received' => 'Appareil Reçu',

            // Contact & Support
            'contact_us' => 'Contactez-nous',
            'customer_support' => 'Support Client',
            'send_message' => 'Envoyer Message',
            'message_sent' => 'Message Envoyé',
            'support_ticket' => 'Ticket de Support',
            'ticket_number' => 'Numéro de Ticket',
            'subject' => 'Sujet',
            'message' => 'Message',
            'attachments' => 'Pièces Jointes',
            'priority' => 'Priorité',
            'high' => 'Élevée',
            'medium' => 'Moyenne',
            'low' => 'Faible',
            'urgent' => 'Urgent',

            // Legal & Information
            'privacy_policy' => 'Politique de Confidentialité',
            'return_policy' => 'Politique de Retour',
            'shipping_policy' => 'Politique d\'Expédition',
            'refund_policy' => 'Politique de Remboursement',
            'about_us' => 'À Propos de Nous',
            'faq' => 'FAQ',
            'help' => 'Aide',
            'size_guide' => 'Guide des Tailles',

            // Search & Filters
            'search_results' => 'Résultats de Recherche',
            'no_results_found' => 'Aucun résultat trouvé',
            'filter_by' => 'Filtrer Par',
            'sort_by' => 'Trier Par',
            'price_range' => 'Gamme de Prix',
            'min_price' => 'Prix Minimum',
            'max_price' => 'Prix Maximum',
            'availability' => 'Disponibilité',
            'customer_rating' => 'Évaluation Client',
            'newest_first' => 'Plus Récent en Premier',
            'oldest_first' => 'Plus Ancien en Premier',
            'price_low_to_high' => 'Prix: Croissant',
            'price_high_to_low' => 'Prix: Décroissant',
            'most_popular' => 'Le Plus Populaire',
            'best_rated' => 'Mieux Noté',

            // Notifications
            'new_notification' => 'Nouvelle Notification',
            'mark_as_read' => 'Marquer comme Lu',
            'clear_all' => 'Tout Effacer',
            'no_notifications' => 'Pas de notifications',

            // Forms & Validation
            'required_field' => 'Ce champ est requis',
            'invalid_email' => 'Veuillez entrer une adresse email valide',
            'passwords_dont_match' => 'Les mots de passe ne correspondent pas',
            'min_length' => 'Longueur minimale requise',
            'max_length' => 'Longueur maximale dépassée',
            'invalid_format' => 'Format invalide',
            'please_select' => 'Veuillez sélectionner',
            'choose_file' => 'Choisir un Fichier',
            'file_uploaded' => 'Fichier téléchargé avec succès',
            'upload_failed' => 'Échec du téléchargement',

            // Time & Date
            'today' => 'Aujourd\'hui',
            'yesterday' => 'Hier',
            'tomorrow' => 'Demain',
            'this_week' => 'Cette Semaine',
            'last_week' => 'Semaine Dernière',
            'this_month' => 'Ce Mois',
            'last_month' => 'Mois Dernier',
            'this_year' => 'Cette Année',
            'days_ago' => 'jours passés',
            'hours_ago' => 'heures passées',
            'minutes_ago' => 'minutes passées',
            'just_now' => 'À l\'instant',

            // Page Titles
            'gadget_garage' => 'Garage de Gadgets',
            'homepage' => 'Page d\'Accueil',
            'product_page' => 'Page Produit',
            'cart_page' => 'Panier',
            'checkout_page' => 'Paiement',
            'login_page' => 'Connexion',
            'register_page' => 'Inscription',
            'account_page' => 'Mon Compte',
            'orders_page' => 'Mes Commandes',
            'wishlist_page' => 'Ma Liste de Souhaits',
            'contact_page' => 'Contactez-nous',
            'about_page' => 'À Propos',

            // Footer
            'footer_description' => 'Votre partenaire de confiance pour les appareils technologiques reconditionnés premium et les services de réparation professionnels.',
            'quick_links' => 'Liens Rapides',
            'customer_service' => 'Service Client',
            'follow_us' => 'Suivez-nous',
            'newsletter' => 'Newsletter',
            'subscribe' => 'S\'abonner',
            'email_address' => 'Adresse Email',
            'subscribe_newsletter' => 'Abonnez-vous à notre newsletter pour les mises à jour et offres',
            'copyright' => '© 2024 Garage de Gadgets. Tous droits réservés.',

            // Meta Descriptions & SEO
            'meta_description' => 'Appareils technologiques reconditionnés premium et services de réparation professionnels chez Garage de Gadgets. Qualité garantie.',
            'meta_keywords' => 'technologie reconditionnée, smartphones, ordinateurs portables, caméras, services de réparation, appareils technologiques',

            // Homepage Specific
            'ipad_pro_title' => 'Apple IPad Pro 11<br>Écran Ultra Retina XDR<br>, 256GB',
            'gadget_garage_title' => 'Garage de Gadgets - Appareils Technologiques Reconditionnés Premium et Services de Réparation',
            'shop_by_categories' => 'Acheter par Catégories',
            'exclusive_offers' => 'Offres Exclusives',
            'best_deals' => 'Meilleures Offres',
            'trending_products' => 'Produits Tendance',
            'customer_testimonials' => 'Témoignages de Clients',
            'why_choose_us' => 'Pourquoi Nous Choisir',
            'quality_guarantee' => 'Garantie de Qualité',
            'fast_shipping' => 'Livraison Rapide',
            'expert_support' => 'Support Expert',
            'secure_payment' => 'Paiement Sécurisé',
            'starting_at' => 'À partir de',
            't900_ultra_watch' => 'Montre T900<br>Ultra',
            'kids_wireless_headphones' => 'Casques Sans Fil<br>Pour Enfants',
            'starting' => 'À partir de',

            // Footer Content
            'services' => 'Services',
            'device_repair' => 'Réparation d\'Appareils',
            'tech_support' => 'Support Technique',
            'data_recovery' => 'Récupération de Données',
            'setup_services' => 'Services d\'Installation',
            'warranty' => 'Garantie',
            'company' => 'Entreprise',
            'careers' => 'Carrières',
            'blog' => 'Blog',
            'press' => 'Presse',
            'support' => 'Support',
            'help_center' => 'Centre d\'Aide',
            'shipping_info' => 'Informations d\'Expédition',
            'returns' => 'Retours',
            'terms_of_service' => 'Conditions de Service',
            'smartphones_footer' => 'Smartphones',
            'laptops_footer' => 'Ordinateurs Portables',
            'tablets' => 'Tablettes',
            'cameras_footer' => 'Caméras',
            'video_equipment_footer' => 'Équipement Vidéo',
        ],

        'de' => [
            // Header & Navigation
            'search_placeholder' => 'Suchen Sie Telefone, Laptops, Kameras...',
            'tech_revival' => 'Bringen Sie Ausgemusterte Technik',
            'home' => 'STARTSEITE',
            'shop' => 'SHOP',
            'mobile_devices' => 'Mobile Geräte',
            'smartphones' => 'Smartphones',
            'ipads' => 'iPads',
            'computing' => 'Computing',
            'laptops' => 'Laptops',
            'desktops' => 'Desktops',
            'photography_video' => 'Fotografie & Video',
            'cameras' => 'Kameras',
            'video_equipment' => 'Videoausrüstung',
            'shop_all' => 'Alles Einkaufen',
            'new_arrivals' => 'Neue Ankünfte',
            'latest_tech_gadgets' => 'Neueste Tech-Gadgets',
            'shop_now' => 'Jetzt Einkaufen',
            'repair_studio' => 'REPARATUR STUDIO',
            'device_drop' => 'GERÄT ABGABE',
            'more' => 'MEHR',
            'contact' => 'Kontakt',
            'terms_conditions' => 'Geschäftsbedingungen',
            'flash_deal' => '⚡ BLITZ ANGEBOT',
            'shop_by_brands' => 'NACH MARKEN EINKAUFEN',
            'all_brands' => 'Alle Marken',
            'all_products' => 'Alle Produkte',

            // User menu & Authentication
            'profile_picture' => 'Profilbild',
            'language' => 'Sprache',
            'dark_mode' => 'Dunkler Modus',
            'my_orders' => 'Meine Bestellungen',
            'wishlist' => 'Wunschliste',
            'notifications' => 'Benachrichtigungen',
            'admin_panel' => 'Admin Panel',
            'logout' => 'Abmelden',
            'register' => 'Registrieren',
            'login' => 'Anmelden',
            'email' => 'E-Mail',
            'password' => 'Passwort',
            'confirm_password' => 'Passwort bestätigen',
            'first_name' => 'Vorname',
            'last_name' => 'Nachname',
            'phone' => 'Telefon',
            'address' => 'Adresse',
            'city' => 'Stadt',
            'country' => 'Land',
            'create_account' => 'Konto erstellen',
            'sign_in' => 'Anmelden',
            'forgot_password' => 'Passwort vergessen?',
            'remember_me' => 'An mich erinnern',

            // Common Actions
            'welcome' => 'Willkommen',
            'add_to_cart' => 'In den Warenkorb',
            'buy_now' => 'Jetzt Kaufen',
            'price' => 'Preis',
            'quantity' => 'Menge',
            'total' => 'Gesamt',
            'subtotal' => 'Zwischensumme',
            'checkout' => 'Zur Kasse',
            'continue_shopping' => 'Weiter Einkaufen',
            'view_cart' => 'Warenkorb Anzeigen',
            'empty_cart' => 'Warenkorb Leeren',
            'remove' => 'Entfernen',
            'update' => 'Aktualisieren',
            'save' => 'Speichern',
            'cancel' => 'Abbrechen',
            'yes' => 'Ja',
            'no' => 'Nein',
            'ok' => 'OK',
            'error' => 'Fehler',
            'success' => 'Erfolg',
            'warning' => 'Warnung',
            'info' => 'Information',
            'loading' => 'Wird geladen...',
            'edit' => 'Bearbeiten',
            'delete' => 'Löschen',
            'add' => 'Hinzufügen',
            'search' => 'Suchen',
            'filter' => 'Filtern',
            'sort' => 'Sortieren',
            'apply' => 'Anwenden',
            'reset' => 'Zurücksetzen',
            'submit' => 'Absenden',
            'back' => 'Zurück',
            'next' => 'Weiter',
            'previous' => 'Vorherige',
            'close' => 'Schließen',

            // Product & Shopping
            'product_name' => 'Produktname',
            'product_description' => 'Produktbeschreibung',
            'product_details' => 'Produktdetails',
            'product_specifications' => 'Produktspezifikationen',
            'product_reviews' => 'Produktbewertungen',
            'add_to_wishlist' => 'Zur Wunschliste hinzufügen',
            'remove_from_wishlist' => 'Von Wunschliste entfernen',
            'in_stock' => 'Auf Lager',
            'out_of_stock' => 'Ausverkauft',
            'limited_stock' => 'Begrenzter Vorrat',
            'condition' => 'Zustand',
            'brand' => 'Marke',
            'category' => 'Kategorie',
            'sku' => 'SKU',
            'warranty' => 'Garantie',
            'rating' => 'Bewertung',
            'reviews' => 'Bewertungen',
            'related_products' => 'Ähnliche Produkte',
            'recently_viewed' => 'Kürzlich angesehen',
            'featured_products' => 'Empfohlene Produkte',

            // Cart & Checkout
            'shopping_cart' => 'Warenkorb',
            'cart_empty' => 'Ihr Warenkorb ist leer',
            'cart_items' => 'Warenkorb-Artikel',
            'item_added_to_cart' => 'Artikel zum Warenkorb hinzugefügt',
            'item_removed_from_cart' => 'Artikel aus Warenkorb entfernt',
            'cart_updated' => 'Warenkorb aktualisiert',
            'proceed_to_checkout' => 'Zur Kasse gehen',
            'billing_address' => 'Rechnungsadresse',
            'shipping_address' => 'Lieferadresse',
            'payment_method' => 'Zahlungsmethode',
            'order_summary' => 'Bestellübersicht',
            'shipping_cost' => 'Versandkosten',
            'tax' => 'Steuer',
            'discount' => 'Rabatt',
            'grand_total' => 'Gesamtsumme',
            'place_order' => 'Bestellung aufgeben',
            'order_placed' => 'Bestellung erfolgreich aufgegeben',
            'order_number' => 'Bestellnummer',
            'order_date' => 'Bestelldatum',
            'order_status' => 'Bestellstatus',

            // Order Management
            'pending' => 'Ausstehend',
            'processing' => 'In Bearbeitung',
            'shipped' => 'Versendet',
            'delivered' => 'Geliefert',
            'cancelled' => 'Storniert',
            'refunded' => 'Erstattet',
            'track_order' => 'Bestellung verfolgen',
            'order_history' => 'Bestellverlauf',
            'reorder' => 'Erneut bestellen',
            'download_receipt' => 'Quittung herunterladen',

            // Admin Panel
            'dashboard' => 'Dashboard',
            'products' => 'Produkte',
            'categories' => 'Kategorien',
            'brands' => 'Marken',
            'orders' => 'Bestellungen',
            'customers' => 'Kunden',
            'reports' => 'Berichte',
            'settings' => 'Einstellungen',
            'add_product' => 'Produkt hinzufügen',
            'edit_product' => 'Produkt bearbeiten',
            'delete_product' => 'Produkt löschen',
            'add_category' => 'Kategorie hinzufügen',
            'edit_category' => 'Kategorie bearbeiten',
            'delete_category' => 'Kategorie löschen',
            'add_brand' => 'Marke hinzufügen',
            'edit_brand' => 'Marke bearbeiten',
            'delete_brand' => 'Marke löschen',
            'manage_orders' => 'Bestellungen verwalten',
            'view_order' => 'Bestellung anzeigen',
            'update_status' => 'Status aktualisieren',

            // Repair Services
            'repair_services' => 'Reparaturservice',
            'device_repair' => 'Gerätereparatur',
            'screen_replacement' => 'Bildschirm-Austausch',
            'battery_replacement' => 'Akku-Austausch',
            'water_damage' => 'Wasserschaden',
            'software_issues' => 'Software-Probleme',
            'hardware_repair' => 'Hardware-Reparatur',
            'diagnosis' => 'Diagnose',
            'repair_quote' => 'Reparatur-Kostenvoranschlag',
            'book_repair' => 'Reparatur buchen',
            'repair_appointment' => 'Reparatur-Termin',
            'appointment_date' => 'Termin-Datum',
            'appointment_time' => 'Termin-Zeit',
            'repair_specialist' => 'Reparatur-Spezialist',
            'repair_status' => 'Reparatur-Status',
            'estimated_cost' => 'Geschätzte Kosten',
            'repair_completed' => 'Reparatur abgeschlossen',

            // Device Drop Service
            'device_drop_service' => 'Geräte-Abgabe-Service',
            'drop_off_device' => 'Gerät abgeben',
            'pickup_device' => 'Gerät abholen',
            'device_condition' => 'Gerätezustand',
            'drop_location' => 'Abgabeort',
            'pickup_time' => 'Abholzeit',
            'schedule_drop' => 'Abgabe planen',
            'drop_confirmed' => 'Abgabe bestätigt',
            'device_received' => 'Gerät erhalten',

            // Contact & Support
            'contact_us' => 'Kontaktieren Sie uns',
            'customer_support' => 'Kundensupport',
            'send_message' => 'Nachricht senden',
            'message_sent' => 'Nachricht gesendet',
            'support_ticket' => 'Support-Ticket',
            'ticket_number' => 'Ticket-Nummer',
            'subject' => 'Betreff',
            'message' => 'Nachricht',
            'attachments' => 'Anhänge',
            'priority' => 'Priorität',
            'high' => 'Hoch',
            'medium' => 'Mittel',
            'low' => 'Niedrig',
            'urgent' => 'Dringend',

            // Legal & Information
            'privacy_policy' => 'Datenschutzrichtlinie',
            'return_policy' => 'Rückgaberichtlinie',
            'shipping_policy' => 'Versandrichtlinie',
            'refund_policy' => 'Erstattungsrichtlinie',
            'about_us' => 'Über uns',
            'faq' => 'FAQ',
            'help' => 'Hilfe',
            'size_guide' => 'Größentabelle',

            // Search & Filters
            'search_results' => 'Suchergebnisse',
            'no_results_found' => 'Keine Ergebnisse gefunden',
            'filter_by' => 'Filtern nach',
            'sort_by' => 'Sortieren nach',
            'price_range' => 'Preisspanne',
            'min_price' => 'Mindestpreis',
            'max_price' => 'Höchstpreis',
            'availability' => 'Verfügbarkeit',
            'customer_rating' => 'Kundenbewertung',
            'newest_first' => 'Neueste zuerst',
            'oldest_first' => 'Älteste zuerst',
            'price_low_to_high' => 'Preis: Niedrig bis Hoch',
            'price_high_to_low' => 'Preis: Hoch bis Niedrig',
            'most_popular' => 'Beliebteste',
            'best_rated' => 'Bestbewertet',

            // Notifications
            'new_notification' => 'Neue Benachrichtigung',
            'mark_as_read' => 'Als gelesen markieren',
            'clear_all' => 'Alle löschen',
            'no_notifications' => 'Keine Benachrichtigungen',

            // Forms & Validation
            'required_field' => 'Dieses Feld ist erforderlich',
            'invalid_email' => 'Bitte geben Sie eine gültige E-Mail-Adresse ein',
            'passwords_dont_match' => 'Passwörter stimmen nicht überein',
            'min_length' => 'Mindestlänge erforderlich',
            'max_length' => 'Maximale Länge überschritten',
            'invalid_format' => 'Ungültiges Format',
            'please_select' => 'Bitte auswählen',
            'choose_file' => 'Datei auswählen',
            'file_uploaded' => 'Datei erfolgreich hochgeladen',
            'upload_failed' => 'Upload fehlgeschlagen',

            // Time & Date
            'today' => 'Heute',
            'yesterday' => 'Gestern',
            'tomorrow' => 'Morgen',
            'this_week' => 'Diese Woche',
            'last_week' => 'Letzte Woche',
            'this_month' => 'Dieser Monat',
            'last_month' => 'Letzter Monat',
            'this_year' => 'Dieses Jahr',
            'days_ago' => 'Tage her',
            'hours_ago' => 'Stunden her',
            'minutes_ago' => 'Minuten her',
            'just_now' => 'Gerade jetzt',

            // Page Titles
            'gadget_garage' => 'Gadget Garage',
            'homepage' => 'Startseite',
            'product_page' => 'Produktseite',
            'cart_page' => 'Warenkorb',
            'checkout_page' => 'Kasse',
            'login_page' => 'Anmelden',
            'register_page' => 'Registrieren',
            'account_page' => 'Mein Konto',
            'orders_page' => 'Meine Bestellungen',
            'wishlist_page' => 'Meine Wunschliste',
            'contact_page' => 'Kontakt',
            'about_page' => 'Über uns',

            // Footer
            'footer_description' => 'Ihr vertrauensvoller Partner für hochwertige refurbished Tech-Geräte und professionelle Reparaturservices.',
            'quick_links' => 'Schnellzugriff',
            'customer_service' => 'Kundenservice',
            'follow_us' => 'Folgen Sie uns',
            'newsletter' => 'Newsletter',
            'subscribe' => 'Abonnieren',
            'email_address' => 'E-Mail-Adresse',
            'subscribe_newsletter' => 'Abonnieren Sie unseren Newsletter für Updates und Angebote',
            'copyright' => '© 2024 Gadget Garage. Alle Rechte vorbehalten.',

            // Meta Descriptions & SEO
            'meta_description' => 'Hochwertige refurbished Tech-Geräte und professionelle Reparaturservices bei Gadget Garage. Qualität garantiert.',
            'meta_keywords' => 'refurbished technik, smartphones, laptops, kameras, reparaturservices, tech-geräte',

            // Homepage Specific
            'ipad_pro_title' => 'Apple IPad Pro 11<br>Ultra Retina XDR<br>Display, 256GB',
            'gadget_garage_title' => 'Gadget Garage - Premium Refurbished Tech-Geräte & Reparaturservices',
            'shop_by_categories' => 'Nach Kategorien Einkaufen',
            'exclusive_offers' => 'Exklusive Angebote',
            'best_deals' => 'Beste Angebote',
            'trending_products' => 'Trending Produkte',
            'customer_testimonials' => 'Kundenbewertungen',
            'why_choose_us' => 'Warum Uns Wählen',
            'quality_guarantee' => 'Qualitätsgarantie',
            'fast_shipping' => 'Schneller Versand',
            'expert_support' => 'Experten-Support',
            'secure_payment' => 'Sichere Bezahlung',
            'starting_at' => 'Ab',
            't900_ultra_watch' => 'T900 Ultra<br>Uhr',
            'kids_wireless_headphones' => 'Kabellose<br>Kinderkopfhörer',
            'starting' => 'Ab',

            // Footer Content
            'services' => 'Dienstleistungen',
            'device_repair' => 'Gerätereparatur',
            'tech_support' => 'Tech-Support',
            'data_recovery' => 'Datenrettung',
            'setup_services' => 'Setup-Services',
            'warranty' => 'Garantie',
            'company' => 'Unternehmen',
            'careers' => 'Karrieren',
            'blog' => 'Blog',
            'press' => 'Presse',
            'support' => 'Support',
            'help_center' => 'Hilfecenter',
            'shipping_info' => 'Versandinfo',
            'returns' => 'Rücksendungen',
            'terms_of_service' => 'Nutzungsbedingungen',
            'smartphones_footer' => 'Smartphones',
            'laptops_footer' => 'Laptops',
            'tablets' => 'Tablets',
            'cameras_footer' => 'Kameras',
            'video_equipment_footer' => 'Videoausrüstung',
        ]
    ];
}

// Load translations
load_translations();
?>